lab_1/urls.py
from django.urls import path
from .views import index
from .views import friend_list

urlpatterns = [
    path('', index, name='index'),
    # TODO Add friends path using friend_list Views
    path('friends/', friend_list, name='friends')
]

lab_2/urls.py
from django.urls import path
from .views import index, xml, json

urlpatterns = [
    path('', index, name='index'),
    path('xml', xml, name='xml'),
    path('json', json, name='json'),
]

lab_3/urls.py
from django.urls import path
from .views import index, add_friend

urlpatterns = [
    path('', index, name='index'),
    path('add', add_friend, name='add_friend'),
]

lab_4/urls.py
from django.urls import path
from .views import index, add_note, note_list

urlpatterns = [
    path('', index, name='index'),
    path('add-note', add_note, name='add_note'),
    path('note-list', note_list, name='note_list'),
]

lab_5/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name='index'),
    path('/notes/<id>', name='notes_id'),
    path('/notes/<id>/update', name='notes_id_update'),
    path('/notes/<id>/delete', name='notes_id_delete'),
]

praktikum/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
import lab_1.urls as lab_1
from lab_1.views import index as index_lab1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
#import lab_5.urls as lab_5

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include('lab_1.urls')),
    re_path(r'^$', index_lab1, name='index'),
    path('lab-2/', include('lab_2.urls')),
    path('lab-3/', include('lab_3.urls')),
    path('lab-4/', include('lab_4.urls')),
    #path('lab-5/', include('lab_5.urls')),
]

lab_1/models.py
from django.db import models

# TODO Create Friend model that contains name, npm, and DOB (date of birth) here


class Friend(models.Model):
    name = models.CharField(max_length=30)
    # TODO Implement missing attributes in Friend model
    npm = models.CharField(max_length=10)
    DOB = models.DateField()

lab_2/models.py
from django.db import models

# Create your models here.
class Note(models.Model):
    to = models.CharField(max_length=30)
    sender = models.CharField(max_length=30)
    title = models.CharField(max_length=200)
    message = models.CharField(max_length=1000)
    

lab_3/models.py
from django.db import models

# Create your models here.

# Will be using model from lab_1.models.Friend

lab_4/models.py
from django.db import models

# Create your models here.

# Will be using model from lab_2.models.Note

lab_5/models.py
from django.db import models

# Create your models here.

lab_3/forms.py
from django.forms import ModelForm
from lab_1.models import Friend as FriendModel

class FriendForm(ModelForm):
	class Meta:
		model = FriendModel
		fields = ['name','npm','DOB']
		

lab_4/forms.py
from django.forms import ModelForm
from django import forms
from lab_2.models import Note as NoteModel

class NoteForm(ModelForm):
	class Meta:
		model = NoteModel
		fields = ['to','sender','title','message']
		
		

lab_5/forms.py
from django.forms import ModelForm
from django import forms
from lab_2.models import Note as NoteModel

class NoteForm(ModelForm):
	class Meta:
		model = NoteModel
		fields = ['to','sender','title','message']

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Friend

mhs_name = 'Hanif Ibrahim Syuaib'  # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2002, 8, 10)  # TODO Implement this, format (Year, Month, Date)
npm = 2006482003  # TODO Implement this


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friends = Friend.objects.all()  # TODO Implement this
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
# Create your views here.
from django.http.response import HttpResponse
from django.core import serializers
from django.shortcuts import render
from .models import Note

def index(request):
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'lab2.html', response)

def xml(request):
    data = serializers.serialize('xml', Note.objects.all())
    return HttpResponse(data, content_type="application/xml")

def json(request):
	data = serializers.serialize('json', Note.objects.all())	    
	return HttpResponse(data, content_type="application/json")

lab_3/views.py
# Create your views here.
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from lab_1.models import Friend
from .forms import FriendForm

@login_required(login_url='/admin/login/')
def index(request):
    friends = Friend.objects.all() 
    response = {'friends': friends}
    return render(request, 'lab3_index.html', response)

@login_required(login_url='/admin/login/')
def add_friend(request):
    form = FriendForm(request.POST or None)
   
    if (request.method == 'POST') :
        if (form.is_valid) :
            form.save()

            return HttpResponseRedirect('/lab-3/')
        
    response = {'form': form}
    return render(request, 'lab3_form.html', response)

lab_4/views.py
# Create your views here.
from django.http import HttpResponseRedirect
from django.shortcuts import render
from lab_2.models import Note
from .forms import NoteForm

def index(request):
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'lab4_index.html', response)

def add_note(request):
    form = NoteForm(request.POST or None)
   
    if (request.method == 'POST') :
        if (form.is_valid) :
            form.save()

            return HttpResponseRedirect('/lab-4/')
        
    response = {'form': form}
    return render(request, 'lab4_form.html', response)

def note_list(request):
	# card format
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'lab4_note_list.html', response)
 

lab_5/views.py
# Create your views here.
from django.http.response import HttpResponse
from django.shortcuts import render
from lab_2.models import Note

def index(request):
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'lab5_index.html', response)

def get_note(request):
	return render(request, 'lab5_index.html', response)

def update_note(request):
	return render(request, 'lab5_index.html', response)

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      {% for friend in friends %}
      <tr>
        <td>{{ friend.name }}</td>
        <td>{{ friend.npm }}</td>
        <td>{{ friend.DOB }}</td>
      </tr>  
      {% endfor %}
      <!-- EXAMPLE SECTION -->
      <tr>
        <td>Asmara Nugi</td>
        <td>1706032156</td>
        <td>May 1, 1999</td>
      </tr>
      <tr>
        <td>Fadli Rais</td>
        <td>1706032370</td>
        <td>Sept 11, 1998</td>
      </tr>
      <!-- END SECTION -->
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Note List</title>
  </head>
  <style>
    table, th, td {
      border: 1px solid black;
    }
    th, td {
      padding: 10px;
    }
  </style>
  <body>
    <table>
      <tr>
        <th>To</th>
        <th>From</th>
        <th>Title</th>
        <th>Message</th>
      </tr>
      <!-- START LOOP SECTION -->
      {% for note in notes %}
      <tr>
        <td>{{ note.to }}</td>
        <td>{{ note.sender }}</td>
        <td>{{ note.title }}</td>
        <td>{{ note.message }}</td>
      </tr>  
      {% endfor %}
      <!-- END LOOP SECTION -->
    </table>
  </body>
</html>

lab_3/templates/lab3_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Form</title>
    <h1>Form - Add Friend</h1>
  </head>
  <body>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <p>Note: DOB format YYYY-MM-DD</p>
        <input type="submit" value="Submit">
    </form>
  </body>
</html>

lab_3/templates/lab3_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
    <style>
    table, th, td {
      border: 1px solid black;
    }
    th, td {
      padding: 10px;
    }
    </style>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- Loop from Friend model -->
      {% for friend in friends %}
      <tr>
        <td>{{ friend.name }}</td>
        <td>{{ friend.npm }}</td>
        <td>{{ friend.DOB }}</td>
      </tr>  
      {% endfor %}
    </table>
  </body>
</html>

lab_4/templates/lab4_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Form - Add Note</title>
    <style>
      .navbar {
        overflow: hidden;
        background-color: #333333;
        font-family: sans-serif;
      }

      .navbar a {
        float: left;
        color: #F2F2F2;
        text-align: center;
        padding: 13px 15px;
        text-decoration: none;
        font-size: 17px;
        font-weight: bold;
      }

      .navbar a:hover {
        background-color: #DDDDDD;
        color: black;
      }

      .custom-form {
        margin: 30px 0;
        width: 500px;
        font-size: 17px;
        font-weight: bold;
        background: #FCD2D1;
        padding: 30px 30px 15px 30px;
        border: 5px solid #FF5C58;
      }

      .custom-form input[type=text],
      .custom-form input[type=submit],
      .custom-form input[type=button],
      .custom-form label {
        font-family: sans-serif;
        font-size: 15px;
        color: #FF5C58;
      }

      .custom-form label {
        display: block;
        margin-bottom: 10px;
      }

      .custom-form label > span {
        display: inline-block;
        float: left;
        width: 100px;
      }

      .custom-form input[type=text] {
        background: transparent;
        border: none;
        border-bottom: 1px dashed #FE8F8F;
        width: 400px;
        outline: none;
        padding: 0px 0px 0px 0px;
      }

      .custom-form input[type=submit],
      .custom-form input[type=button], {
        background: #FFEDD3;
        border: none;
        padding: 8px 10px 8px 10px;
        color: #FFEDD3;
        font-weight: bold;
      }

      .custom-form input[type=submit]:hover,
      .custom-form input[type=button]:hover {
        background: #FE8F8F;
        color: white;
        font-weight: bold;
      }
    </style>
  </head>
  <body>
    <div class="navbar">
      <a href="http://localhost:8000/lab-4"           style="color: #F9CF93;">Home</a>
      <a href="http://localhost:8000/lab-4/add-note"  style="color: #FE8F8F;">Add Note</a>
      <a href="http://localhost:8000/lab-4/note-list" style="color: #57CC99;">Note List</a>
    </div>
    <form class="custom-form" action="" method="POST">
      {% csrf_token %}
      <label for="id_to">
        <span>Send to</span><input id="id_to" type="text" name="to" required="true"/>
      </label>
      <label for="id_sender">
        <span>Sender</span><input id="id_sender" type="text" name="sender" required="true"/>
      </label>
      <label for="id_title">
        <span>Title</span><input id="id_title" type="text" name="title" required="true"/>
      </label>
      <label for="id_message">
        <span>Message</span><input id="id_message" type="text" name="message" required="true"/>
      </label>
      <br>
      <label>
        <span> </span><input type="submit" value="Send" style="float: right;" />
      </label>
      <br>
    </form>
  </body>
</html>

lab_4/templates/lab4_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Home - Note</title>
    <style>
      .navbar {
        overflow: hidden;
        background-color: #333333;
        font-family: sans-serif;
      }

      .navbar a {
        float: left;
        color: #F2F2F2;
        text-align: center;
        padding: 13px 15px;
        text-decoration: none;
        font-size: 17px;
        font-weight: bold;
      }

      .navbar a:hover {
        background-color: #DDDDDD;
        color: black;
      }

      .custom-table {
        border-collapse: collapse;
        margin: 30px 0;
        font-size: 15px;
        font-family: sans-serif;
        min-width: 300px;
      }

      .custom-table thead tr {
        background-color: #F9CF93;
        color: #FFFFFF;
        text-align: left;
        font-weight: bold;
      }

      .custom-table th, 
      .custom-table td {
        padding: 12px 15px;
      }

      .custom-table tbody tr {
        border-bottom: 1px solid #DBD0C0;
      }

      .custom-table tbody tr:nth-of-type(even) {
        background-color: #F9E4C8;
      }

      .custom-table tbody tr:last-of-type {
        border-bottom: 2px solid #F9CF93;
      }
    </style>
  </head>
  <body>
    <div class="navbar">
      <a href="http://localhost:8000/lab-4"           style="color: #F9CF93;">Home</a>
      <a href="http://localhost:8000/lab-4/add-note"  style="color: #FE8F8F;">Add Note</a>
      <a href="http://localhost:8000/lab-4/note-list" style="color: #57CC99;">Note List</a>
    </div>
    <table class="custom-table">
      <thead>
        <tr>
          <th>To</th>
          <th>From</th>
          <th>Title</th>
          <th>Message</th>
        </tr>
      </thead>  
      <tbody>
        <!-- START LOOP SECTION -->
        {% for note in notes %}
        <tr>
          <td>{{ note.to }}</td>
          <td>{{ note.sender }}</td>
          <td>{{ note.title }}</td>
          <td>{{ note.message }}</td>
        </tr>  
        {% endfor %}
        <!-- END LOOP SECTION -->
      </tbody>
    </table>
  </body>
</html>

lab_4/templates/lab4_note_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Note List</title>
    <style>
      .navbar {
        overflow: hidden;
        background-color: #333333;
        font-family: sans-serif;
      }

      .navbar a {
        float: left;
        color: #F2F2F2;
        text-align: center;
        padding: 13px 15px;
        text-decoration: none;
        font-size: 17px;
        font-weight: bold;
      }

      .navbar a:hover {
        background-color: #DDDDDD;
        color: black;
      }

      .card {
        margin: 10px 0;
        width: 350px;
        float: none;
        padding: 8px;
      }

      .field {
        list-style-type: none;
        border: 2px solid #22577A;
        margin: 0;
        padding: 0;
      }

      .field li {
        border-bottom: 1px solid #22577A;
        padding: 10px;
        text-align: center;
      }

      .field .header {
        background-color: #38A3A5;
        font-size: 17px;
        color: white;
        padding: 5px;
      }

      .field .input {
        background-color: #80ED99;
        font-size: 15px;
      }
    </style>
  </head>
  <body>
    <div class="navbar">
      <a href="http://localhost:8000/lab-4"           style="color: #F9CF93;">Home</a>
      <a href="http://localhost:8000/lab-4/add-note"  style="color: #FE8F8F;">Add Note</a>
      <a href="http://localhost:8000/lab-4/note-list" style="color: #57CC99;">Note List</a>
    </div>
    <!-- START LOOP SECTION -->
    {% for note in notes %}
      <div class="card"> 
        <ul class="field">
          <li class="header">To</li>
          <li class="input">{{ note.to }}</li>
          <li class="header">From</li>
          <li class="input">{{ note.sender }}</li>
          <li class="header">Title</li>
          <li class="input">{{ note.title }}</li>
          <li class="header">Message</li>
          <li class="input">{{ note.message }}</li>
        </ul>  
      </div> 
    {% endfor %}
    <!-- END LOOP SECTION -->
  </body>
</html>

lab_5/templates/lab5_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Home - Note</title>
    <style>
      .navbar {
        overflow: hidden;
        background-color: #333333;
        font-family: sans-serif;
      }

      .navbar a {
        float: left;
        color: #F2F2F2;
        text-align: center;
        padding: 13px 15px;
        text-decoration: none;
        font-size: 17px;
        font-weight: bold;
      }

      .navbar a:hover {
        background-color: #DDDDDD;
        color: black;
      }

      .custom-table {
        border-collapse: collapse;
        margin: 30px 0;
        font-size: 15px;
        font-family: sans-serif;
        min-width: 300px;
      }

      .custom-table thead tr {
        background-color: #F9CF93;
        color: #FFFFFF;
        text-align: left;
        font-weight: bold;
      }

      .custom-table th, 
      .custom-table td {
        padding: 12px 15px;
      }

      .custom-table tbody tr {
        border-bottom: 1px solid #DBD0C0;
      }

      .custom-table tbody tr:nth-of-type(even) {
        background-color: #F9E4C8;
      }

      .custom-table tbody tr:last-of-type {
        border-bottom: 2px solid #F9CF93;
      }
    </style>
  </head>
  <body>
    <div class="navbar">
      <a href="http://localhost:8000/lab-4"           style="color: #F9CF93;">Home</a>
      <a href="http://localhost:8000/lab-4/add-note"  style="color: #FE8F8F;">Add Note</a>
      <a href="http://localhost:8000/lab-4/note-list" style="color: #57CC99;">Note List</a>
    </div>
    <table class="custom-table">
      <thead>
        <tr>
          <th>To</th>
          <th>From</th>
          <th>Title</th>
          <th>Message</th>
          <th>Actions</th>
        </tr>
      </thead>  
      <tbody>
        <!-- START LOOP SECTION -->
        {% for note in notes %}
        <tr>
          <td>{{ note.to }}</td>
          <td>{{ note.sender }}</td>
          <td>{{ note.title }}</td>
          <td>{{ note.message }}</td>
          <td>
            <button type="button" formaction="">View</button>
            <button type="button" formaction="">Edit</button>
            <button type="button" formaction="">Delete</button>
          </td>
        </tr>  
        {% endfor %}
        <!-- END LOOP SECTION -->
      </tbody>
    </table>
  </body>
</html>